{{- $values := include "childcharts.metric.crds.values" . | fromYaml -}}
{{- $metricValues := get .Values "metric" | default dict -}}
{{- $extraValues := get $metricValues "extra" | default dict -}}
{{- $parentGlobal := get $extraValues "global" | default dict -}}
{{- $componentValues := get $metricValues "crds" | default dict -}}
{{- $global := mustMergeOverwrite (deepCopy ((get $values "global") | default dict)) $parentGlobal -}}
{{- $ctxMetric := dict "extra" $extraValues -}}
{{- $ctxValues := mustMergeOverwrite (deepCopy $values) (dict "global" $global "metric" $ctxMetric) -}}
{{- $ctx := dict "Values" $ctxValues "Release" .Release "Chart" .Chart "Capabilities" .Capabilities "Files" .Files "Template" .Template -}}
{{- if or (not (hasKey $componentValues "enabled")) (get $componentValues "enabled") -}}
{{- with $ctx -}}
{{- $ctxRoot := . -}}
{{- if .Values.upgradeJob.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "childcharts.metric.crds.upgradeJob.name" . }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "childcharts.metric.crds.upgradeJob.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ template "kube-prometheus-stack.namespace" . }}
    name: {{ template "childcharts.metric.crds.upgradeJob.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "childcharts.metric.crds.upgradeJob.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- end -}}
{{- end -}}
