{{- $values := include "childcharts.metric.crds.values" . | fromYaml -}}
{{- $metricValues := get .Values "metric" | default dict -}}
{{- $extraValues := get $metricValues "extra" | default dict -}}
{{- $parentGlobal := get $extraValues "global" | default dict -}}
{{- $componentValues := get $metricValues "crds" | default dict -}}
{{- $global := mustMergeOverwrite (deepCopy ((get $values "global") | default dict)) $parentGlobal -}}
{{- $ctxMetric := dict "extra" $extraValues -}}
{{- $ctxValues := mustMergeOverwrite (deepCopy $values) (dict "global" $global "metric" $ctxMetric) -}}
{{- $ctx := dict "Values" $ctxValues "Release" .Release "Chart" .Chart "Capabilities" .Capabilities "Files" .Files "Template" .Template -}}
{{- if or (not (hasKey $componentValues "enabled")) (get $componentValues "enabled") -}}
{{- with $ctx -}}
{{- $ctxRoot := . -}}
{{- if and .Values.upgradeJob.enabled .Values.upgradeJob.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.upgradeJob.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ include "childcharts.metric.crds.upgradeJob.serviceAccountName" . }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- with .Values.upgradeJob.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "childcharts.metric.crds.upgradeJob.labels" . | nindent 4 }}
    {{- with .Values.upgradeJob.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}

{{- end -}}
{{- end -}}
