{{- $root := . -}}
{{- $values := include "childcharts.tracing.deepflow-agent.values" . | fromYaml -}}
{{- $ctxValues := mustMergeOverwrite (dict "global" .Values.tracing.global) (deepCopy $values) -}}
{{- $ctx := dict "Values" $ctxValues "Release" .Release "Chart" .Chart "Capabilities" .Capabilities "Files" .Files "Template" .Template -}}
{{- if and .Values.tracing.enabled $values.enabled }}
{{- with $ctx }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "childcharts.tracing.deepflow-agent.fullname" $root }}
  labels:
    {{- include "childcharts.tracing.deepflow-agent.labels" $root | nindent 4 }}
data:
  {{- tpl (toYaml .Values.deepflowAgentConfig) . | nindent 2 }}
{{- end }}
{{- end }}
