{{- $root := . -}}
{{- $values := include "childcharts.tracing.deepflow-agent.values" . | fromYaml -}}
{{- $ctxValues := mustMergeOverwrite (dict "global" .Values.tracing.global) (deepCopy $values) -}}
{{- $ctx := dict "Values" $ctxValues "Release" .Release "Chart" .Chart "Capabilities" .Capabilities "Files" .Files "Template" .Template -}}
{{- if and .Values.tracing.enabled $values.enabled (has "daemonset" $values.deployComponent) }}
{{- with $ctx }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "childcharts.tracing.deepflow-agent.fullname" $root }}
  labels:
    {{- include "childcharts.tracing.deepflow-agent.labels" $root | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "childcharts.tracing.deepflow-agent.selectorLabels" $root | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ toYaml .Values.deepflowAgentConfig | sha256sum }}
        checksum/customConfig: {{ toYaml .Values.deepflowAgentConfig | sha256sum }}
        container.apparmor.security.beta.kubernetes.io/deepflow-agent: unconfined
        {{- if .Values.tkeSidecar }}
        eks.tke.cloud.tencent.com/ds-injection: "true"
        {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "childcharts.tracing.deepflow-agent.selectorLabels" $root | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      dnsPolicy: {{ tpl .Values.dnsPolicy $root }}
      hostNetwork: {{ tpl .Values.hostNetwork $root }}
      hostPID: true
      imagePullSecrets:
      {{- with .Values.global.imagePullSecrets }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "childcharts.tracing.deepflow-agent.fullname" $root }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.sysctlInitContainer.enabled }}
      initContainers:
      - name: configure-sysctl
        securityContext:
          runAsUser: 0
          privileged: true
        image: "{{ tpl .Values.image.repository $root }}:{{ tpl (toString .Values.image.tag) $root }}"
        imagePullPolicy: {{ tpl .Values.image.pullPolicy $root }}
        command: ["/bin/bash", "-c", "sysctl -w net.core.bpf_jit_enable=1 || true"]
      {{- end }}
      containers:
        - name: deepflow-agent
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ tpl .Values.image.repository $root }}:{{ tpl (toString .Values.image.tag) $root }}"
          imagePullPolicy: {{ tpl .Values.image.pullPolicy $root }}
          {{- if .Values.tkeSidecar }}
          command:
          - /usr/bin/deepflow-agent
          args:
          - --sidecar
          - -f
          - /etc/deepflow-agent/deepflow-agent.yaml
          {{- end }}
          ports:
            - name: receive
              containerPort: {{ tpl (toString .Values.externalAgentHttpProxyPort) $root }}
              protocol: TCP
          env:
          - name: TZ
            value: {{ tpl .Values.timezone $root }}
          - name: K8S_NAMESPACE_FOR_DEEPFLOW
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: K8S_NODE_IP_FOR_DEEPFLOW
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: K8S_NODE_NAME_FOR_DEEPFLOW
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: K8S_POD_NAME_FOR_DEEPFLOW
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          {{- if .Values.tkeSidecar }}
          - name: CTRL_NETWORK_INTERFACE
            value: "eth0"
          {{- end }}
          {{- if .Values.daemonsetWatchDisabled }}
          - name: K8S_WATCH_POLICY
            value: "watch-disabled"
          {{- end }}
          - name: K8S_POD_IP_FOR_DEEPFLOW
            valueFrom:
              fieldRef:
              {{- if .Values.tkeSidecar }}
                fieldPath: status.hostIP
              {{- else }}
                fieldPath: status.podIP
              {{- end }}
          {{- range .Values.env }}
          - name: {{ .name }}
            value: {{ .value }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: sys-kernel-debug
              mountPath: /sys/kernel/debug
              readOnly: true
            - name: deepflow-agent-conf
              mountPath: /etc/deepflow-agent
            {{- if .Values.netns.mount }}
            - name: netns
              mountPath: /var/run/netns
              readOnly: true
              mountPropagation: HostToContainer
            {{- end }}
          {{- range .Values.extraVolumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath | default "" }}
              readOnly: {{ .readOnly }}
          {{- end }}
      volumes:
        {{- if .Values.netns.mount }}
        - name: netns
          hostPath:
            path: /var/run/netns
            type: DirectoryOrCreate
        {{- end }}
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
        - name: deepflow-agent-conf
          configMap:
            name: {{ include "childcharts.tracing.deepflow-agent.fullname" $root }}
      {{- range .Values.extraVolumeMounts }}
        - name: {{ .name }}
          {{- if .existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .existingClaim }}
          {{- else if .hostPath }}
          hostPath:
            path: {{ .hostPath }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
{{ include "childcharts.tracing.deepflow-agent.nodeaffinity" . | nindent 8 }}
{{ include "childcharts.tracing.deepflow-agent.podAffinity" . | nindent 8 }}
{{ include "childcharts.tracing.deepflow-agent.podAntiAffinity" . | nindent 8 }}
      {{- if or .Values.global.tolerations .Values.tolerations }}
      tolerations:
      {{- if .Values.global.tolerations }}
      {{- toYaml .Values.global.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- end }}
{{- end }}
{{- end }}
