apiVersion: v2
appVersion: 6.5.0
description: An automated observability platform for cloud-native developers.
home: https://github.com/deepflowio/deepflow
icon: https://raw.githubusercontent.com/deepflowio/deepflow-charts/main/deepflow.svg
keywords:
- deepflow
kubeVersion: '>=1.16.0-0'
maintainers:
- name: deepflow
  url: https://github.com/deepflowio/deepflow
name: stella-agent-ce
sources:
- https://github.com/deepflowio/deepflow
type: application
version: 6.5.001
