{{- $mergedClickhouseValues := include "childcharts.tracing.clickhouse.values" . | fromYaml -}}
{{- $ctxChart := dict "Name" "clickhouse" "Version" "0.1.000" "AppVersion" "21.8.15.7" -}}
{{- if and .Values.tracing.enabled .Values.tracing.clickhouse.enabled }}
{{- $ctx := dict "Values" $mergedClickhouseValues "Release" .Release "Chart" $ctxChart "Capabilities" .Capabilities "Files" .Files "Template" .Template -}}
{{- with $ctx -}}
{{- $root := . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "childcharts.tracing.clickhouse.fullname" . }}
  labels:
    {{- include "childcharts.tracing.clickhouse.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
{{- if ne .Values.service.type "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}
  ports:
  {{- $serviceType := .Values.service.type -}}
  {{- range .Values.service.ports }}
  - name: {{ tpl .name $root }}
    port: {{ tpl (toString .port) $root }}
    targetPort: {{ tpl (toString .targetPort) $root }}
    {{- if and (eq $serviceType "NodePort") (.nodePort) }}
    nodePort: {{ tpl (toString .nodePort) $root }}
    {{- end }}
    protocol: {{ tpl .protocol $root }}
  {{- end }}
{{- if .Values.service.additionalPorts }}
{{ toYaml .Values.service.additionalPorts | indent 2 }}
{{- end }}
  selector:
    {{- include "childcharts.tracing.clickhouse.selectorLabels" . | nindent 4 }}
  type: "{{ .Values.service.type }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "childcharts.tracing.clickhouse.fullname" . }}-headless
  labels:
    {{- include "childcharts.tracing.clickhouse.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  {{- range .Values.service.ports }}
  - name: {{ tpl .name $root }}
    port: {{ tpl (toString .port) $root }}
    targetPort: {{ tpl (toString .targetPort) $root }}
    protocol: {{ tpl .protocol $root }}
  {{- end }}
  selector:
    {{- include "childcharts.tracing.clickhouse.selectorLabels" . | nindent 4 }}
  type: ClusterIP
{{- end }}
{{- end }}
