{{- $mergedClickhouseValues := include "childcharts.tracing.clickhouse.values" . | fromYaml -}}
{{- $ctxChart := dict "Name" "clickhouse" "Version" "0.1.000" "AppVersion" "21.8.15.7" -}}
{{- if and .Values.tracing.enabled .Values.tracing.clickhouse.enabled }}
{{- $ctx := dict "Values" $mergedClickhouseValues "Release" .Release "Chart" $ctxChart "Capabilities" .Capabilities "Files" .Files "Template" .Template -}}
{{- with $ctx -}}
{{- $root := . -}}
{{- $storageType := include "childcharts.tracing.clickhouse.storageType" . | trim }}
{{- $chmodContainer := get .Values "chmodContainer" | default (dict "enabled" true) }}
{{- if and (not $root.Values.global.allInOneLocalStorage ) (eq $storageType "hostPath") (not $root.Values.nodeAffinityLabelSelector)  }}
{{- fail "You must set nodeAffinityLabelSelector"  -}}
{{- end}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "childcharts.tracing.clickhouse.fullname" . }}
  labels:
    {{- include "childcharts.tracing.clickhouse.labels" . | nindent 4 }}
spec:
  replicas: {{ tpl (toString .Values.replicas) . }}
  podManagementPolicy: {{ tpl .Values.podManagementPolicy . }}
  serviceName: {{ include "childcharts.tracing.clickhouse.fullname" . }}-headless
  selector:
    matchLabels:
      {{- include "childcharts.tracing.clickhouse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "childcharts.tracing.clickhouse.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      hostNetwork: {{ tpl (toString .Values.hostNetwork) . }}
      dnsPolicy: {{ tpl .Values.dnsPolicy . }}
      imagePullSecrets:
      {{- with .Values.global.imagePullSecrets }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if $chmodContainer.enabled }}
      initContainers:
        - name: clickhouse-init
          image: "{{ tpl .Values.image.repository . }}:{{ tpl (toString .Values.image.tag) . }}"
          volumeMounts:
          - name: clickhouse-path
            mountPath: /var/lib/clickhouse/
          - name: clickhouse-storage-path
            mountPath: /var/lib/clickhouse_storage/
          command: ['sh', '-c', 'chown clickhouse:clickhouse /var/lib/clickhouse_storage;chown clickhouse:clickhouse /var/lib/clickhouse/']
      {{- end }}
      containers:
        - name: clickhouse
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ tpl .Values.image.repository . }}:{{ tpl (toString .Values.image.tag) . }}"
          imagePullPolicy: {{ tpl .Values.image.pullPolicy . }}
          env:
            - name: TZ
              value: "{{ tpl .Values.timezone . }}"
          ports:
            - name: tcp
              containerPort: 9000
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: tcp
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: tcp
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: clickhouse-config
            mountPath: /etc/clickhouse-server/
          - name: clickhouse-path
            mountPath: /var/lib/clickhouse/
          - name: clickhouse-storage-path
            mountPath: /var/lib/clickhouse_storage/
        {{- range .Values.storageConfig.extraClickhousePath }}
          - name: {{ .volumeName }}
            mountPath: {{ .mountPath }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
      {{- include "childcharts.tracing.clickhouse.nodeaffinity" . | indent 6 }}
      {{- include "childcharts.tracing.clickhouse.podAffinity" . | indent 6 }}
      {{- include "childcharts.tracing.clickhouse.podAntiAffinity" . | indent 6 }}
      {{- if or .Values.global.tolerations .Values.tolerations }}
      tolerations:
      {{- if .Values.global.tolerations }}
      {{- toYaml .Values.global.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- end }}
      volumes:
        - name: clickhouse-config
          configMap:
            name: {{ include "childcharts.tracing.clickhouse.fullname" . }}-config
      {{- if eq $storageType "hostPath" }}
        - name: clickhouse-path
          hostPath:
            path: {{ tpl .Values.storageConfig.hostPath . }}/clickhouse
            type: DirectoryOrCreate
        - name: clickhouse-storage-path
          hostPath:
            path: {{ tpl .Values.storageConfig.hostPath . }}/clickhouse-storage
            type: DirectoryOrCreate
      {{- end }}
  {{- if eq $storageType "persistentVolumeClaim" }}
  volumeClaimTemplates:
  {{- include "childcharts.tracing.clickhouse.persistentVolumeClaim" . | indent 2 }}
  {{- end }}
{{- end }}
{{- end }}
