{
 "title": "展示v2",
 "tags": [ "linux" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   { "name": "datasource", "query": "prometheus" },
   { "name": "Deployment", "query": { "query": "label_values(deployment)" } },
   { "name": "Statefulset", "query": { "query": "label_values(statefulset)" } },
   { "name": "Daemonset", "query": { "query": "label_values(daemonset)" } },
   { "name": "Node", "query": { "query": "label_values()" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kepler_container_package_joules_total,container_namespace)"
    }
   },
   { "name": "container", "query": { "query": "label_values()" } },
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values(nvidia_smi_index,uuid)"
    }
   },
   { "name": "coal", "label": "Coal Coeff", "query": "2.23" },
   { "name": "natural_gas", "label": "Natural Gas Coeff", "query": "0.91" },
   { "name": "petroleum", "label": "Petroleum Coeff", "query": "2.13" },
   { "name": "watt_per_second_to_kWh", "query": "${VAR_WATT_PER_SECOND_TO_KWH}" },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kepler_container_package_joules_total{container_namespace=~\"$namespace\"},pod_name)"
    }
   },
   { "name": "Hostname", "query": { "query": "label_values()" } },
   { "name": "fpga", "query": { "query": "label_values()" } }
  ]
 },
 "panels": [
  { "type": "canvas", "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 14, "x": 5, "y": 0 },
   "options": {
    "content": "\r\n<center><b><font size = \"10\">6G 无线网络云平台</font></b></center>\r\n\r\n\r\n\r\n"
   }
  },
  { "type": "canvas", "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; justify-content: center; height: 70%; background-color: purple; color: white; font-size: 5vw;\">\r\n    <font size=\"5\" style=\"margin-left: 5px;\">Resource Overview\r\n    </font>\r\n</div>\r\n\r\n\r\n\r\n\r\n"
   }
  },
  {
   "title": "容器总能耗(单位千瓦时)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kepler_node_package_joules_total) / 3600000"
    }
   ]
  },
  {
   "title": "节点数量",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kubelet_node_name{node!=\"dpu1\"})"
    }
   ]
  },
  {
   "title": "容器数量",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace!=\"\"})"
    }
   ]
  },
  {
   "title": "CPU 使用率",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (sum(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[5m])) / sum(rate(node_cpu_seconds_total{instance=\"$node\"}[5m]))))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{instance=\"$node\"} / node_memory_MemTotal_bytes{instance=\"$node\"}))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_filesystem_avail_bytes{mountpoint=\"/\", fstype!=\"nfs4\", fstype!=\"tmpfs\", fstype!=\"overlay\",instance=\"$node\"} / node_filesystem_size_bytes{mountpoint=\"/\", fstype!=\"nfs4\", fstype!=\"tmpfs\", fstype!=\"overlay\",instance=\"$node\"}))"
    }
   ]
  },
  {
   "title": "平台容器状况",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{}) by (phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "kubelet_running_pod_count{kubernetes_io_role =~ \".*node.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU使用情况",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"system\"}[5m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[5m])))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"user\"}[5m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[5m])))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"iowait\"}[5m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[5m])))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=~\".*irq\"}[5m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[5m])))",
     "legendFormat": "Busy IRQs"
    }
   ]
  },
  {
   "title": "内存的使用情况",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Used"
    }
   ]
  },
  {
   "title": "磁盘空间使用情况",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\", fstype!=\"nfs4\", fstype!=\"tmpfs\", fstype!=\"overlay\", instance=\"$node\"}",
     "legendFormat": "Disk_Free"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\", fstype!=\"nfs4\", fstype!=\"tmpfs\", fstype!=\"overlay\", instance=\"$node\"} - node_filesystem_avail_bytes{mountpoint=\"/\", fstype!=\"nfs4\", fstype!=\"tmpfs\", fstype!=\"overlay\", instance=\"$node\"}",
     "legendFormat": "Disk_Used"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 18 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; justify-content: center; height: 70%; background-color: purple; color: white; font-size: 5vw;\">\r\n    <font size=\"6\" style=\"margin-left: 5px;\">GPU\r\n    </font>\r\n</div>\r\n\r\n\r\n\r\n\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 18 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; justify-content: center; height: 70%; background-color: purple; color: white; font-size: 5vw;\">\r\n    <font size=\"6\" style=\"margin-left: 5px;\">FPGA\r\n    </font>\r\n</div>\r\n\r\n\r\n\r\n\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 18 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; justify-content: center; height: 70%; background-color: purple; color: white; font-size: 5vw;\">\r\n    <font size=\"6\" style=\"margin-left: 5px;\">DPU\r\n    </font>\r\n</div>\r\n\r\n\r\n\r\n\r\n"
   }
  },
  {
   "title": "云化GPU实例",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_FB_FREE{UUID!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU平均功耗",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_power_draw_watts{uuid=\"$gpu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "云化FPGA实例",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(xilinx_fpga_memory_utilization{name=\"bank0\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FPGA平均功耗",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "xilinx_fpga_Power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "虚拟网卡实例",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kubelet_node_name{node!=\"dpu1\"}) + 30",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "虚拟网卡使用",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kubelet_node_name{node!=\"dpu1\"}) + 16",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU显存使用",
   "type": "timeseries",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nvidia_smi_memory_used_bytes{uuid=\"$gpu\"}",
     "legendFormat": "Gpu_Memory_Used"
    }
   ]
  },
  {
   "title": "FPGA内存使用",
   "type": "timeseries",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum(xilinx_fpga_memory_usage{name!=\"\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "网络流量（收发包）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{instance=\"$node\",job=\"$job\"}[1d])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{instance=\"$node\",job=\"$job\"}[1d])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  }
 ]
}