{{- if .Values.customer.enabled -}}
{{- if .Values.customer.nvidiaGpuExporter.enabled -}}
{{- if .Values.customer.nvidiaGpuExporter.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nvidia-gpu-exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nvidia-gpu-exporter.labels" . | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
