{{- if and .Values.metric.enabled .Values.metric.kepler.enabled .Values.metric.kepler.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kepler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kepler.labels" . | nindent 4 }}
  {{- with .Values.metric.kepler.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
