{{- if and .Values.logging.enabled .Values.logging.kibana.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pre-install-{{ include "kibana.uname" . }}
  labels: {{ include "kibana.labels" . | nindent 4 }}
  # annotations:
  #   "helm.sh/hook": pre-install,pre-upgrade
  #   "helm.sh/hook-delete-policy": hook-succeeded
  #   {{- if .Values.logging.kibana.annotations }}
  #   {{- range $key, $value := .Values.logging.kibana.annotations }}
  #   {{ $key }}: {{ $value | quote }}
  #   {{- end }}
  #   {{- end }}
subjects:
  - kind: ServiceAccount
    name: pre-install-{{ include "kibana.uname" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: pre-install-{{ include "kibana.uname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
