{{- if and .Values.metric.enabled .Values.metric.prometheusOperator.enabled .Values.metric.prometheusOperator.networkPolicy.enabled (eq .Values.metric.prometheusOperator.networkPolicy.flavor "kubernetes") }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "kube-prometheus-stack.operator.fullname" . }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    {{- include "kube-prometheus-stack.prometheus-operator.labels" . | nindent 4 }}
spec:
  egress:
    - {}
  ingress:
    - ports:
      {{- if .Values.metric.prometheusOperator.tls.enabled }}
      - port: {{ .Values.metric.prometheusOperator.tls.internalPort }}
      {{- else }}
      - port: 8080
      {{- end }}
  policyTypes:
    - Egress
    - Ingress
  podSelector:
    matchLabels:
      app: {{ template "kube-prometheus-stack.name" . }}-operator
      release: {{ $.Release.Name | quote }}
      {{- if .Values.metric.prometheusOperator.networkPolicy.matchLabels }}
      {{ toYaml .Values.metric.prometheusOperator.networkPolicy.matchLabels | nindent 6 }}
      {{- end }}
{{- end }}
