{{- if and .Values.metric.enabled .Values.metric.prometheusOperator.enabled .Values.metric.prometheusOperator.admissionWebhooks.enabled .Values.metric.prometheusOperator.admissionWebhooks.patch.enabled (not .Values.metric.prometheusOperator.admissionWebhooks.certManager.enabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ template "kube-prometheus-stack.fullname" . }}-admission-create
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
{{- with .Values.metric.prometheusOperator.admissionWebhooks.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ template "kube-prometheus-stack.name" $ }}-admission-create
    {{- include "kube-prometheus-stack.prometheus-operator-webhook.labels" $ | nindent 4 }}
spec:
  ttlSecondsAfterFinished: {{ .Values.metric.prometheusOperator.admissionWebhooks.patch.ttlSecondsAfterFinished }}
  template:
    metadata:
      name:  {{ template "kube-prometheus-stack.fullname" . }}-admission-create
{{- with .Values.metric.prometheusOperator.admissionWebhooks.patch.podAnnotations }}
      annotations:
{{ toYaml .  | indent 8 }}
{{- end }}
      labels:
        app: {{ template "kube-prometheus-stack.name" $ }}-admission-create
        {{- include "kube-prometheus-stack.prometheus-operator-webhook.labels" $ | nindent 8 }}
    spec:
      {{- if .Values.metric.prometheusOperator.admissionWebhooks.patch.priorityClassName }}
      priorityClassName: {{ .Values.metric.prometheusOperator.admissionWebhooks.patch.priorityClassName }}
      {{- end }}
      {{- if .Values.metric.extra.global.imagePullSecrets }}
      imagePullSecrets:
      {{- include "kube-prometheus-stack.imagePullSecrets" . | indent 8 }}
      {{- end }}
      containers:
        - name: create
          {{- $registry := .Values.metric.extra.global.imageRegistry | default .Values.metric.prometheusOperator.admissionWebhooks.patch.image.registry -}}
          {{- if .Values.metric.prometheusOperator.admissionWebhooks.patch.image.sha }}
          image: {{ $registry }}/{{ .Values.metric.prometheusOperator.admissionWebhooks.patch.image.repository }}:{{ .Values.metric.prometheusOperator.admissionWebhooks.patch.image.tag }}@sha256:{{ .Values.metric.prometheusOperator.admissionWebhooks.patch.image.sha }}
          {{- else }}
          image: {{ $registry }}/{{ .Values.metric.prometheusOperator.admissionWebhooks.patch.image.repository }}:{{ .Values.metric.prometheusOperator.admissionWebhooks.patch.image.tag }}
          {{- end }}
          imagePullPolicy: {{ .Values.metric.prometheusOperator.admissionWebhooks.patch.image.pullPolicy }}
          args:
            - create
            - --host={{- include "kube-prometheus-stack.operator.admission-webhook.dnsNames" . | replace "\n" "," }}
            - --namespace={{ template "kube-prometheus-stack.namespace" . }}
            - --secret-name={{ template "kube-prometheus-stack.fullname" . }}-admission
          {{- with .Values.metric.prometheusOperator.admissionWebhooks.createSecretJob }}
          securityContext:
          {{ toYaml .securityContext | nindent 12 }}
          {{- end }}
          resources:
{{ toYaml .Values.metric.prometheusOperator.admissionWebhooks.patch.resources | indent 12 }}
      restartPolicy: OnFailure
      serviceAccountName: {{ template "kube-prometheus-stack.fullname" . }}-admission
      {{- with .Values.metric.prometheusOperator.admissionWebhooks.patch.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.metric.prometheusOperator.admissionWebhooks.patch.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.metric.prometheusOperator.admissionWebhooks.patch.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- if .Values.metric.prometheusOperator.admissionWebhooks.patch.securityContext }}
      securityContext:
{{ toYaml .Values.metric.prometheusOperator.admissionWebhooks.patch.securityContext | indent 8 }}
{{- end }}
{{- end }}
