{{- if and .Values.metric.enabled .Values.metric.prometheusOperator.networkPolicy.enabled (eq .Values.metric.prometheusOperator.networkPolicy.flavor "kubernetes") }}
{{- if and .Values.metric.prometheusOperator.enabled .Values.metric.prometheusOperator.admissionWebhooks.enabled .Values.metric.prometheusOperator.admissionWebhooks.patch.enabled (not .Values.metric.prometheusOperator.admissionWebhooks.certManager.enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name:  {{ template "kube-prometheus-stack.fullname" . }}-admission-patch
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    ## Ensure this is run before the job
    "helm.sh/hook-weight": "-5"
    {{- with .Values.metric.prometheusOperator.admissionWebhooks.patch.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app: {{ template "kube-prometheus-stack.name" $ }}-admission-patch
    {{- include "kube-prometheus-stack.prometheus-operator-webhook.labels" $ | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "kube-prometheus-stack.name" $ }}-admission-patch
      {{- if .Values.metric.prometheusOperator.networkPolicy.matchLabels }}
      {{ toYaml .Values.metric.prometheusOperator.networkPolicy.matchLabels | nindent 6 }}
      {{- else }}
      {{- include "kube-prometheus-stack.prometheus-operator-webhook.labels" $ | nindent 6 }}
      {{- end }}
  egress:
  - {}
  policyTypes:
  - Egress
{{- end }}
{{- end }}
