{{- if and .Values.metric.enabled .Values.metric.prometheus.enabled .Values.metric.prometheus.networkPolicy.enabled (eq .Values.metric.prometheus.networkPolicy.flavor "kubernetes") }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-prometheus
    {{- include "kube-prometheus-stack.labels" . | nindent 4 }}
  name: {{ template "kube-prometheus-stack.fullname" . }}-prometheus
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
spec:
  {{- if .Values.metric.prometheus.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.metric.prometheus.networkPolicy.egress | nindent 4 }}
  {{- end }}
  {{- if .Values.metric.prometheus.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.metric.prometheus.networkPolicy.ingress | nindent 4 }}
  {{- end }}
  policyTypes:
    - Egress
    - Ingress
  podSelector:
    {{- if .Values.metric.prometheus.networkPolicy.podSelector }}
    {{- toYaml .Values.metric.prometheus.networkPolicy.podSelector | nindent 4 }}
    {{- else }}
    matchLabels:
      {{- if .Values.metric.prometheus.agentMode }}
      app.kubernetes.io/name: prometheus-agent
      {{- else }}
      app.kubernetes.io/name: prometheus
      {{- end }}
      operator.prometheus.io/name: {{ template "kube-prometheus-stack.prometheus.crname" . }}
    {{- end }}
{{- end }}
