{{- if and .Values.metric.enabled .Values.metric.prometheus.enabled .Values.metric.prometheus.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-prometheus
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-prometheus
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  {{- if .Values.metric.prometheus.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.metric.prometheus.podDisruptionBudget.minAvailable }}
  {{- end  }}
  {{- if .Values.metric.prometheus.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.metric.prometheus.podDisruptionBudget.maxUnavailable }}
  {{- end  }}
  selector:
    matchLabels:
      {{- if .Values.metric.prometheus.agentMode }}
      app.kubernetes.io/name: prometheus-agent
      {{- else }}
      app.kubernetes.io/name: prometheus
      {{- end }}
      operator.prometheus.io/name: {{ template "kube-prometheus-stack.prometheus.crname" . }}
{{- end }}
