{{- if and .Values.metric.enabled .Values.metric.prometheus.enabled .Values.metric.prometheus.prometheusSpec.thanos .Values.metric.prometheus.prometheusSpec.thanos.objectStorageConfig}}
{{- if and .Values.metric.prometheus.prometheusSpec.thanos.objectStorageConfig.secret (not .Values.metric.prometheus.prometheusSpec.thanos.objectStorageConfig.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-prometheus
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-prometheus
    app.kubernetes.io/component: prometheus
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
data:
  object-storage-configs.yaml: {{ toYaml .Values.metric.prometheus.prometheusSpec.thanos.objectStorageConfig.secret | b64enc | quote }}
{{- end }}
{{- end }}
