{{- if and .Values.metric.enabled .Values.metric.alertmanager.enabled .Values.metric.alertmanager.servicePerReplica.enabled .Values.metric.alertmanager.ingressPerReplica.enabled }}
{{- $pathType := .Values.metric.alertmanager.ingressPerReplica.pathType | default "" }}
{{- $count := .Values.metric.alertmanager.alertmanagerSpec.replicas | int -}}
{{- $servicePort := .Values.metric.alertmanager.service.port -}}
{{- $ingressValues := .Values.metric.alertmanager.ingressPerReplica -}}
apiVersion: v1
kind: List
metadata:
  name: {{ include "kube-prometheus-stack.fullname" $ }}-alertmanager-ingressperreplica
  namespace: {{ template "kube-prometheus-stack-alertmanager.namespace" . }}
items:
{{ range $i, $e := until $count }}
  - kind: Ingress
    apiVersion: networking.k8s.io/v1
    metadata:
      name: {{ include "kube-prometheus-stack.fullname" $ }}-alertmanager-{{ $i }}
      namespace: {{ template "kube-prometheus-stack.namespace" $ }}
      labels:
        app: {{ include "kube-prometheus-stack.name" $ }}-alertmanager
      {{ include "kube-prometheus-stack.labels" $ | indent 8 }}
      {{- if $ingressValues.labels }}
{{ toYaml $ingressValues.labels | indent 8 }}
      {{- end }}
      {{- if $ingressValues.annotations }}
      annotations:
        {{- tpl (toYaml $ingressValues.annotations) $ | nindent 8 }}
      {{- end }}
    spec:
      {{- if $ingressValues.ingressClassName }}
      ingressClassName: {{ $ingressValues.ingressClassName }}
      {{- end }}
      rules:
        - host: {{ $ingressValues.hostPrefix }}-{{ $i }}.{{ $ingressValues.hostDomain }}
          http:
            paths:
      {{- range $p := $ingressValues.paths }}
              - path: {{ tpl $p $ }}
                pathType: {{ $pathType }}
                backend:
                  service:
                    name: {{ include "kube-prometheus-stack.fullname" $ }}-alertmanager-{{ $i }}
                    port:
                      number: {{ $servicePort }}
      {{- end -}}
      {{- if or $ingressValues.tlsSecretName $ingressValues.tlsSecretPerReplica.enabled }}
      tls:
        - hosts:
            - {{ $ingressValues.hostPrefix }}-{{ $i }}.{{ $ingressValues.hostDomain }}
          {{- if $ingressValues.tlsSecretPerReplica.enabled }}
          secretName: {{ $ingressValues.tlsSecretPerReplica.prefix }}-{{ $i }}
          {{- else }}
          secretName: {{ $ingressValues.tlsSecretName }}
          {{- end }}
      {{- end }}
{{- end -}}
{{- end -}}
