{{- if and .Values.metric.enabled .Values.metric.alertmanager.enabled .Values.metric.alertmanager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kube-prometheus-stack.alertmanager.serviceAccountName" . }}
  namespace: {{ template "kube-prometheus-stack-alertmanager.namespace" . }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-alertmanager
    app.kubernetes.io/name: {{ template "kube-prometheus-stack.name" . }}-alertmanager
    app.kubernetes.io/component: alertmanager
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
{{- if .Values.metric.alertmanager.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.metric.alertmanager.serviceAccount.annotations | indent 4 }}
{{- end }}
automountServiceAccountToken: {{ .Values.metric.alertmanager.serviceAccount.automountServiceAccountToken }}
{{- if .Values.metric.extra.global.imagePullSecrets }}
imagePullSecrets:
{{ include "kube-prometheus-stack.imagePullSecrets" . | trim | indent 2}}
{{- end }}
{{- end }}
