global:
  podAntiAffinityLabelSelector: []
  podAntiAffinityTermLabelSelector: []
  podAffinityLabelSelector: []
  podAffinityTermLabelSelector: []
  nodeAffinityLabelSelector: []
  nodeAffinityTermLabelSelector: []
  deepflowServerName: ""

deployComponent:
- "daemonset"

tkeSidecar: false
daemonsetWatchDisabled: false

image:
  repository: xnet.registry.io:8443/observability/deepflow-agent
  pullPolicy: IfNotPresent
  tag: v7.0

env: []

imagePullSecrets: []
nameOverride: ""
agentFullnameOverride: "deepflow-agent"

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
hostNetwork: "false"
dnsPolicy: "ClusterFirst"

nodeIPInjection: true

netns:
  mount: false

securityContext:
  capabilities:
    add:
    - SYS_ADMIN
    - SYS_RESOURCE
    - SYS_PTRACE
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYSLOG

timezone: "Asia/Shanghai"

sysctlInitContainer:
  enabled: true

extraVolumeMounts: []
service:
  annotations: {}
  labels: {}
  clusterIP: ""
  ports:
  - name: receive
    port: 80
    targetPort: receive
    nodePort:
    protocol: TCP
  additionalPorts: []
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  externalTrafficPolicy: Cluster
  type: ClusterIP

deepflowServerNodeIPS:
- '#{RELEASE_NAME}-deepflow-server.#{RELEASE_NAMESPACE}.svc.cluster.local'
kubernetesClusterId:
agentGroupID:
externalAgentHttpProxyPort: 38086

kubernetesApiEnabled: true

deepflowAgentConfig:
  deepflow-agent.yaml: |
    {{- nindent 4 "controller-ips:" -}}
    {{- if .Values.global }}
    {{- if .Values.global.deepflowServerName }}
    {{- $serverName := .Values.global.deepflowServerName }}
    {{- $serverName := regexReplaceAll "#\\{RELEASE_NAME\\}" $serverName $.Release.Name }}
    {{- $serverName := regexReplaceAll "#\\{RELEASE_NAMESPACE\\}" $serverName $.Release.Namespace }}
    {{- nindent 4 "- " }}{{ $serverName }}
    {{- else }}
    {{- range $ip := .Values.deepflowServerNodeIPS -}}
      {{- if eq $ip "\"%DEEPFLOW_SERVER_SERVICE%\"" -}}
      {{- if $.Release.Name -}}
      {{- nindent 4 "- " }}{{ $.Release.Name }}-deepflow-server.{{ $.Release.Namespace }}.svc.cluster.local
      {{- end -}}
      {{- else -}}
      {{- $ip := regexReplaceAll "#\\{RELEASE_NAME\\}" $ip $.Release.Name }}
      {{- $ip := regexReplaceAll "#\\{RELEASE_NAMESPACE\\}" $ip $.Release.Namespace }}
      {{- nindent 4 "- " }}{{ $ip }}
      {{- end -}}
    {{- end -}}
    {{- end }}
    {{- else }}
    {{- range $ip := .Values.deepflowServerNodeIPS -}}
      {{- if eq $ip "\"%DEEPFLOW_SERVER_SERVICE%\"" -}}
      {{- if $.Release.Name -}}
      {{- nindent 4 "- " }}{{ $.Release.Name }}-deepflow-server.{{ $.Release.Namespace }}.svc.cluster.local
      {{- end -}}
      {{- else -}}
      {{- $ip := regexReplaceAll "#\\{RELEASE_NAME\\}" $ip $.Release.Name }}
      {{- $ip := regexReplaceAll "#\\{RELEASE_NAMESPACE\\}" $ip $.Release.Namespace }}
      {{- nindent 4 "- " }}{{ $ip }}
      {{- end -}}
    {{- end -}}
    {{- end }}
    {{- if .Values.agentGroupID }}{{ nindent 4 "vtap-group-id-request:" }} {{ .Values.agentGroupID }}{{ end -}}
    {{- if .Values.deepflowK8sClusterID }}{{ nindent 4 "kubernetes-cluster-id:" }} {{ .Values.deepflowK8sClusterID }}{{ end -}}
    {{- if .Values.controllerPort }}{{ nindent 4 "controller-port:" }} {{ .Values.controllerPort }}{{ end -}}
    {{- if .Values.clusterNAME }}{{ nindent 4 "kubernetes-cluster-name:" }} {{ .Values.clusterNAME }}{{ end -}}
    {{- if .Values.teamId }}{{ nindent 4 "team-id:" }} {{ .Values.teamId }}{{ end -}}
    {{- if hasKey .Values "kubernetesApiEnabled" }}{{ nindent 4 "kubernetes-api-enabled:" }} {{ .Values.kubernetesApiEnabled }}{{ end -}}

resources:
  limits:
    cpu: 1000m
    memory: 768Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300

podAntiAffinityLabelSelector: []
podAntiAffinityTermLabelSelector: []
podAffinityLabelSelector: []
podAffinityTermLabelSelector: []
nodeAffinityLabelSelector: []
nodeAffinityTermLabelSelector: []
