{{- $values := include "childcharts.tracing.byconity.fdb-operator.values" . | fromYaml -}}
{{- $ctxValues := mustMergeOverwrite (dict "global" ((index .Values.tracing "global") | default dict)) (deepCopy $values) -}}
{{- $ctx := dict "Values" $ctxValues "Release" .Release "Chart" .Chart "Capabilities" .Capabilities "Files" .Files "Template" .Template -}}
{{- if and .Values.tracing.enabled ((index .Values.tracing "byconity" "enabled") | default false) ($values.enabled | default false) -}}
{{- with $ctx -}}
{{- $ctxRoot := . -}}
---
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "childcharts.tracing.byconity.fdb-operator.serviceAccountName" . }}
  labels:
    {{- include "childcharts.tracing.byconity.fdb-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}

{{- end -}}
{{- end -}}
