{{- $values := include "childcharts.tracing.byconity.values" . | fromYaml -}}
{{- $ctxValues := mustMergeOverwrite (dict "global" ((index .Values.tracing "global") | default dict)) (deepCopy $values) -}}
{{- $ctx := dict "Values" $ctxValues "Release" .Release "Chart" .Chart "Capabilities" .Capabilities "Files" .Files "Template" .Template -}}
{{- if and .Values.tracing.enabled ((index .Values.tracing "byconity" "enabled") | default false) -}}
{{- with $ctx -}}
{{- $ctxRoot := . -}}
{{ if .Values.byconity.use_existing_fdb }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "childcharts.tracing.byconity.fullname" $ }}-fdb-config
data:
  cluster-file: |
    {{ $ctxRoot.Values.byconity.fdb_cluster_file }}
{{ end }}

{{- end -}}
{{- end -}}
