{{- $values := include "childcharts.tracing.byconity.values" . | fromYaml -}}
{{- $ctxValues := mustMergeOverwrite (dict "global" ((index .Values.tracing "global") | default dict)) (deepCopy $values) -}}
{{- $ctx := dict "Values" $ctxValues "Release" .Release "Chart" .Chart "Capabilities" .Capabilities "Files" .Files "Template" .Template -}}
{{- if and .Values.tracing.enabled ((index .Values.tracing "byconity" "enabled") | default false) -}}
{{- with $ctx -}}
{{- $ctxRoot := . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "childcharts.tracing.byconity.fullname" . }}-worker-run
  labels:
    {{- include "childcharts.tracing.byconity.labels" . | nindent 4 }}
    byconity-role: worker
data:
  run: |
    #!/bin/bash
    chown root. /var/byconity /var/log/byconity
    exec "${APP_ROOT}/bin/clickhouse-server" --config "/etc/byconity/worker.yaml"

{{- range .Values.byconity.virtualWarehouses }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "childcharts.tracing.byconity.fullname" $ }}-vw-{{ .name | replace "_" "-" }}-config
  labels:
    {{- include "childcharts.tracing.byconity.labels" $ | nindent 4 }}
    byconity-role: worker
    byconity-vw: {{ .name }}
data:
  worker.yaml: |
    {{- $ports := dict "tcp_port" $ctxRoot.Values.byconity.ports.tcp "http_port" $ctxRoot.Values.byconity.ports.http "rpc_port" $ctxRoot.Values.byconity.ports.rpc "exchange_port" $ctxRoot.Values.byconity.ports.exchange "exchange_status_port" $ctxRoot.Values.byconity.ports.exchangeStatus }}
    {{- $server_service := dict "service" (printf "%s-%s" (include "childcharts.tracing.byconity.fullname" $) "server") "headless_service" (printf "%s-%s-headless" (include "childcharts.tracing.byconity.fullname" $) "server") "psm" (printf "%s-%s" (include "childcharts.tracing.byconity.fullname" $) "server") }}
    {{- $tso_service := dict "service" (printf "%s-%s" (include "childcharts.tracing.byconity.fullname" $) "tso") "headless_service" (printf "%s-%s-headless" (include "childcharts.tracing.byconity.fullname" $) "tso") "psm" (printf "%s-%s" (include "childcharts.tracing.byconity.fullname" $) "tso") }}
    {{- $dm_service := dict "service" (printf "%s-%s" (include "childcharts.tracing.byconity.fullname" $) "daemon-manager") "headless_service" (printf "%s-%s-headless" (include "childcharts.tracing.byconity.fullname" $) "daemon-manager") "psm" (printf "%s-%s" (include "childcharts.tracing.byconity.fullname" $) "daemon-manager") }}
    {{- $rm_service := dict "service" (printf "%s-%s" (include "childcharts.tracing.byconity.fullname" $) "resource-manager") "headless_service" (printf "%s-%s-headless" (include "childcharts.tracing.byconity.fullname" $) "resource-manager") "psm" (printf "%s-%s" (include "childcharts.tracing.byconity.fullname" $) "resource-manager") }}
    {{- $service_discovery := dict "service_discovery" (dict "server" $server_service "tso" $tso_service "daemon_manager" $dm_service "resource_manager" $rm_service) }}
    {{- $catalog := dict "catalog" (dict "name_space" (include "childcharts.tracing.byconity.fullname" $)) }}
    {{- $hdfs_addr := dict "hdfs_addr" $ctxRoot.Values.byconity.hdfs_address }}
    {{- $ctxRoot.Files.Get "files/childcharts/tracing/byconity/worker.yaml" | fromYaml | merge .configOverwrite $ctxRoot.Values.byconity.configOverwrite $hdfs_addr $catalog $service_discovery $ports | toYaml | nindent 4 }}
  users.yaml: |
    {{- $ctxRoot.Files.Get "files/childcharts/tracing/byconity/users.yaml" | fromYaml | merge $ctxRoot.Values.byconity.usersOverwrite | toYaml | nindent 4 }}
  hdfs3.xml: |
    <configuration>
        {{- range $key, $val := $ctxRoot.Values.byconity.hdfs3Config }}
        <property>
            <name>{{ $key }}</name>
            <value>{{ $val }}</value>
        </property>
        {{- end }}
    </configuration>
  cnch-config.yaml: |
     {{- $ports := dict "tcp_port" $ctxRoot.Values.byconity.ports.tcp "http_port" $ctxRoot.Values.byconity.ports.http "rpc_port" $ctxRoot.Values.byconity.ports.rpc "exchange_port" $ctxRoot.Values.byconity.ports.exchange "exchange_status_port" $ctxRoot.Values.byconity.ports.exchangeStatus }}
     {{- $server_service := dict "service" (printf "%s-%s" (include "childcharts.tracing.byconity.fullname" $) "server") "headless_service" (printf "%s-%s-headless" (include "childcharts.tracing.byconity.fullname" $) "server") "psm" (printf "%s-%s" (include "childcharts.tracing.byconity.fullname" $) "server") }}
     {{- $tso_service := dict "service" (printf "%s-%s" (include "childcharts.tracing.byconity.fullname" $) "tso") "headless_service" (printf "%s-%s-headless" (include "childcharts.tracing.byconity.fullname" $) "tso") "psm" (printf "%s-%s" (include "childcharts.tracing.byconity.fullname" $) "tso") }}
     {{- $dm_service := dict "service" (printf "%s-%s" (include "childcharts.tracing.byconity.fullname" $) "daemon-manager") "headless_service" (printf "%s-%s-headless" (include "childcharts.tracing.byconity.fullname" $) "daemon-manager") "psm" (printf "%s-%s" (include "childcharts.tracing.byconity.fullname" $) "daemon-manager") }}
     {{- $rm_service := dict "service" (printf "%s-%s" (include "childcharts.tracing.byconity.fullname" $) "resource-manager") "headless_service" (printf "%s-%s-headless" (include "childcharts.tracing.byconity.fullname" $) "resource-manager") "psm" (printf "%s-%s" (include "childcharts.tracing.byconity.fullname" $) "resource-manager") }}
     {{- $service_discovery := dict "service_discovery" (dict "server" $server_service "tso" $tso_service "daemon_manager" $dm_service "resource_manager" $rm_service) }}
     {{- $catalog := dict "catalog" (dict "name_space" (include "childcharts.tracing.byconity.fullname" $)) }}
     {{- $hdfs_addr_dict := dict "hdfs_addr" $ctxRoot.Values.byconity.hdfs_address }}
     {{- $hdfs_ha_nameservice_dict := dict "hdfs_ha_nameservice" $ctxRoot.Values.byconity.hdfs_ha_nameservice }}
     {{- $hdfs_addr := (empty $ctxRoot.Values.byconity.hdfs_ha_nameservice | ternary $hdfs_addr_dict $hdfs_ha_nameservice_dict) }}
     {{- $ctxRoot.Files.Get "files/childcharts/tracing/byconity/cnch-config.yaml" | fromYaml | merge .configOverwrite $hdfs_addr $catalog $service_discovery $ports | toYaml | nindent 4 }}
{{- end }}

{{- end -}}
{{- end -}}
