{{- $values := include "childcharts.tracing.byconity.values" . | fromYaml -}}
{{- $ctxValues := mustMergeOverwrite (dict "global" ((index .Values.tracing "global") | default dict)) (deepCopy $values) -}}
{{- $ctx := dict "Values" $ctxValues "Release" .Release "Chart" .Chart "Capabilities" .Capabilities "Files" .Files "Template" .Template -}}
{{- if and .Values.tracing.enabled ((index .Values.tracing "byconity" "enabled") | default false) -}}
{{- with $ctx -}}
{{- $ctxRoot := . -}}
{{- range .Values.byconity.virtualWarehouses }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "childcharts.tracing.byconity.fullname" $ }}-vw-{{ .name | replace "_" "-"}}
  labels:
    {{- include "childcharts.tracing.byconity.labels" $ | nindent 4 }}
    byconity-role: worker
    byconity-vw: {{ .name }}
spec:
  type: ClusterIP
  selector:
    {{- include "childcharts.tracing.byconity.selectorLabels" $ | nindent 4 }}
    byconity-role: worker
  ports:
    - name: port0
      port: {{ $ctxRoot.Values.byconity.ports.tcp }}
      targetPort: tcp
    - name: port1
      port: {{ $ctxRoot.Values.byconity.ports.rpc }}
      targetPort: rpc
    - name: port2
      port: {{ $ctxRoot.Values.byconity.ports.http }}
      targetPort: http
    - name: port3
      port: {{ $ctxRoot.Values.byconity.ports.tcpSecure }}
      targetPort: tcp-secure
    - name: port4
      port: {{ $ctxRoot.Values.byconity.ports.https }}
      targetPort: https
    - name: port5
      port: {{ $ctxRoot.Values.byconity.ports.exchange }}
      targetPort: exchange
    - name: port6
      port: {{ $ctxRoot.Values.byconity.ports.exchangeStatus }}
      targetPort: exchange-status

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "childcharts.tracing.byconity.fullname" $ }}-vw-{{ .name | replace "_" "-"}}-headless
  labels:
    {{- include "childcharts.tracing.byconity.labels" $ | nindent 4 }}
    byconity-role: worker
    byconity-vw: {{ .name }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "childcharts.tracing.byconity.selectorLabels" $ | nindent 4 }}
    byconity-role: worker
  ports:
    - name: port0
      port: {{ $ctxRoot.Values.byconity.ports.tcp }}
      targetPort: tcp
    - name: port1
      port: {{ $ctxRoot.Values.byconity.ports.rpc }}
      targetPort: rpc
    - name: port2
      port: {{ $ctxRoot.Values.byconity.ports.http }}
      targetPort: http
    - name: port3
      port: {{ $ctxRoot.Values.byconity.ports.tcpSecure }}
      targetPort: tcp-secure
    - name: port4
      port: {{ $ctxRoot.Values.byconity.ports.https }}
      targetPort: https
    - name: port5
      port: {{ $ctxRoot.Values.byconity.ports.exchange }}
      targetPort: exchange
    - name: port6
      port: {{ $ctxRoot.Values.byconity.ports.exchangeStatus }}
      targetPort: exchange-status
{{- end }}

{{- end -}}
{{- end -}}
