{{- if and .Values.logging.enabled .Values.logging.filebeat.enabled .Values.logging.filebeat.managedServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "filebeat.serviceAccount" . }}-cluster-role
  labels:
    app: "{{ template "filebeat.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
rules: {{ toYaml .Values.logging.filebeat.clusterRoleRules | nindent 2 -}}
{{- end -}}
