apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.customer.apiserver.serviceAccount.name | default "alert-api" }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: alert-api
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
{{- if .Values.customer.apiserver.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.customer.apiserver.serviceAccount.annotations | indent 4 }}
{{- end }}