{{- $values := include "childcharts.metric.grafana.values" . | fromYaml -}}
{{- $metricValues := get .Values "metric" | default dict -}}
{{- $extraValues := get $metricValues "extra" | default dict -}}
{{- $parentGlobal := get $extraValues "global" | default dict -}}
{{- $componentValues := get $metricValues "grafana" | default dict -}}
{{- $global := mustMergeOverwrite (deepCopy ((get $values "global") | default dict)) $parentGlobal -}}
{{- $ctxValues := mustMergeOverwrite (deepCopy $values) (dict "global" $global) -}}
{{- $ctxChart := dict "Name" "grafana" "Version" "9.2.7" "AppVersion" "12.0.2" -}}
{{- $ctx := dict "Values" $ctxValues "Release" .Release "Chart" $ctxChart "Capabilities" .Capabilities "Files" .Files "Template" .Template -}}
{{- if and (get $metricValues "enabled") (get $componentValues "enabled") -}}
{{- with $ctx -}}
{{- $ctxRoot := . -}}
{{- if and .Values.rbac.create (or (not .Values.rbac.namespaced) .Values.rbac.extraClusterRoleRules) }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "grafana.fullname" . }}-clusterrolebinding
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "grafana.serviceAccountName" . }}
    namespace: {{ include "grafana.namespace" . }}
roleRef:
  kind: ClusterRole
  {{- if .Values.rbac.useExistingClusterRole }}
  name: {{ .Values.rbac.useExistingClusterRole }}
  {{- else }}
  name: {{ include "grafana.fullname" . }}-clusterrole
  {{- end }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- end -}}
{{- end -}}
