{{- $values := include "childcharts.metric.grafana.values" . | fromYaml -}}
{{- $metricValues := get .Values "metric" | default dict -}}
{{- $extraValues := get $metricValues "extra" | default dict -}}
{{- $parentGlobal := get $extraValues "global" | default dict -}}
{{- $componentValues := get $metricValues "grafana" | default dict -}}
{{- $global := mustMergeOverwrite (deepCopy ((get $values "global") | default dict)) $parentGlobal -}}
{{- $ctxValues := mustMergeOverwrite (deepCopy $values) (dict "global" $global) -}}
{{- $ctxChart := dict "Name" "grafana" "Version" "9.2.7" "AppVersion" "12.0.2" -}}
{{- $ctx := dict "Values" $ctxValues "Release" .Release "Chart" $ctxChart "Capabilities" .Capabilities "Files" .Files "Template" .Template -}}
{{- if and (get $metricValues "enabled") (get $componentValues "enabled") -}}
{{- with $ctx -}}
{{- $ctxRoot := . -}}
{{- $sts := list "sts" "StatefulSet" "statefulset" -}}
{{- if or .Values.headlessService (and .Values.persistence.enabled (not .Values.persistence.existingClaim) (has .Values.persistence.type $sts)) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana.fullname" . }}-headless
  namespace: {{ include "grafana.namespace" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  selector:
    {{- include "grafana.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
  - name: {{ .Values.gossipPortName }}-tcp
    port: 9094
{{- end }}

{{- end -}}
{{- end -}}
