{{- $values := include "childcharts.metric.grafana.values" . | fromYaml -}}
{{- $metricValues := get .Values "metric" | default dict -}}
{{- $extraValues := get $metricValues "extra" | default dict -}}
{{- $parentGlobal := get $extraValues "global" | default dict -}}
{{- $componentValues := get $metricValues "grafana" | default dict -}}
{{- $global := mustMergeOverwrite (deepCopy ((get $values "global") | default dict)) $parentGlobal -}}
{{- $ctxValues := mustMergeOverwrite (deepCopy $values) (dict "global" $global) -}}
{{- $ctxChart := dict "Name" "grafana" "Version" "9.2.7" "AppVersion" "12.0.2" -}}
{{- $ctx := dict "Values" $ctxValues "Release" .Release "Chart" $ctxChart "Capabilities" .Capabilities "Files" .Files "Template" .Template -}}
{{- if and (get $metricValues "enabled") (get $componentValues "enabled") -}}
{{- with $ctx -}}
{{- $ctxRoot := . -}}
{{- if and .Values.imageRenderer.enabled .Values.imageRenderer.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana.fullname" . }}-image-renderer
  namespace: {{ include "grafana.namespace" . }}
  labels:
    {{- include "grafana.imageRenderer.labels" . | nindent 4 }}
    {{- with .Values.imageRenderer.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.imageRenderer.service.annotations }}
  annotations:
    {{- tpl (toYaml . | nindent 4) $ctxRoot }}
  {{- end }}
spec:
  type: ClusterIP
  {{- with .Values.imageRenderer.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  ports:
    - name: {{ .Values.imageRenderer.service.portName }}
      port: {{ .Values.imageRenderer.service.port }}
      protocol: TCP
      targetPort: {{ .Values.imageRenderer.service.targetPort }}
      {{- with .Values.imageRenderer.appProtocol }}
      appProtocol: {{ . }}
      {{- end }}
  selector:
    {{- include "grafana.imageRenderer.selectorLabels" . | nindent 4 }}
{{- end }}

{{- end -}}
{{- end -}}
