# InfluxDB StatefulSet
{{- if .Values.customer.dataservice.influxdb2.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-influxdb2
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: influxdb2
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "monitoring-stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: influxdb2
  serviceName: {{ include "monitoring-stack.fullname" . }}-influxdb2
  template:
    metadata:
      labels:
        {{- include "monitoring-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: influxdb2
    spec:
      serviceAccountName: {{ include "monitoring-stack.serviceAccountName" . }}
      containers:
        - name: influxdb2
          image: influxdb:2.7.4-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
              name: http
          env:
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: "setup"
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              value: {{ .Values.customer.dataservice.influxdb2.adminUser.user | quote }}
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              value: {{ .Values.customer.dataservice.influxdb2.adminUser.password | quote }}
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: {{ .Values.customer.dataservice.influxdb2.adminUser.organization | quote }}
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: {{ .Values.customer.dataservice.influxdb2.adminUser.bucket | quote }}
            - name: DOCKER_INFLUXDB_INIT_RETENTION
              value: {{ .Values.customer.dataservice.influxdb2.adminUser.retention_policy | quote }}
            # - name: DOCKER_INFLUXDB_INIT_BUCKET_RETENTION
            #   value: {{ .Values.customer.dataservice.influxdb2.adminUser.bucketRetention | quote }}
            # - name: DOCKER_INFLUXDB_INIT_BUCKET_SHARD_GROUP_DURATION
            #   value: {{ .Values.customer.dataservice.influxdb2.adminUser.bucketShardGroupDuration | quote }}
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              value: {{ .Values.customer.dataservice.influxdb2.adminUser.token | quote }}
            - name: INFLUXD_STORAGE_CACHE_MAX_MEMORY_SIZE	
              value: {{ .Values.customer.dataservice.influxdb2.adminUser.storageCacheMaxMemorySize | quote }}
            - name: INFLUXD_STORAGE_CACHE_SNAPSHOT_MEMORY_SIZE	
              value: {{ .Values.customer.dataservice.influxdb2.adminUser.storageCacheSnapshotMemorySize | quote }}
            - name: INFLUXD_STORAGE_TSM_USE_MADV_WILLNEED
              value: {{ .Values.customer.dataservice.influxdb2.adminUser.storageTsmUseMadvWillneed | quote }}
            - name: INFLUXD_STORAGE_CACHE_SNAPSHOT_WRITE_COLD_DURATION
              value: {{ .Values.customer.dataservice.influxdb2.adminUser.storageCacheSnapshotWriteColdDuration | quote }}
            - name: INFLUXD_STORAGE_COMPACT_FULL_WRITE_COLD_DURATION
              value: {{ .Values.customer.dataservice.influxdb2.adminUser.storageCompactFullWriteColdDuration | quote }}
            - name: INFLUXD_STORAGE_COMPACT_THROUGHPUT_BURST	
              value: {{ .Values.customer.dataservice.influxdb2.adminUser.storageCompactThroughputBurst | quote }}
            - name: INFLUXD_STORAGE_WAL_FSYNC_DELAY	
              value: {{ .Values.customer.dataservice.influxdb2.adminUser.storageWalFsyncDelay | quote }}
            # - name: INFLUXD_QUERY_MAX_MEMORY_BYTES	
            #   value: {{ .Values.customer.dataservice.influxdb2.adminUser.queryMaxMemoryBytes | quote }}
            - name: INFLUXD_STORAGE_TSM_USE_MADV_WILLNEED
              value: {{ .Values.customer.dataservice.influxdb2.adminUser.storageTsmUseMadvWillneed | quote }}
            - name: INFLUXD_STORAGE_SERIES_ID_SET_CACHE_SIZE
              value: {{ .Values.customer.dataservice.influxdb2.adminUser.storageSeriesIdSetCacheSize | quote }}
            - name: INFLUXD_QUERY_CONCURRENCY
              value: {{ .Values.customer.dataservice.influxdb2.adminUser.queryConcurrency | quote }}
          resources:
            limits:
              cpu: {{ .Values.customer.dataservice.influxdb2.resources.limits.cpu | quote }}
              memory: {{ .Values.customer.dataservice.influxdb2.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.customer.dataservice.influxdb2.resources.requests.cpu | quote }}
              memory: {{ .Values.customer.dataservice.influxdb2.resources.requests.memory | quote }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/influxdb2
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "monitoring-stack.fullname" . }}-influxdb2
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "monitoring-stack.labels" . | nindent 10 }}
          app.kubernetes.io/component: influxdb2
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: "50Gi"
{{- end }}