# Telegraf Service
{{- if .Values.customer.dataservice.telegraf.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-telegraf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: telegraf
spec:
  type: ClusterIP
  ports:
    - name: statsd-udp
      port: 8125
      targetPort: 8125
      protocol: UDP
    - name: statsd-tcp
      port: 8125
      targetPort: 8125
      protocol: TCP
  selector:
    {{- include "monitoring-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: telegraf
{{- end }}