{{- $values := include "childcharts.metric.prometheus-node-exporter.values" . | fromYaml -}}
{{- $metricValues := get .Values "metric" | default dict -}}
{{- $extraValues := get $metricValues "extra" | default dict -}}
{{- $parentGlobal := get $extraValues "global" | default dict -}}
{{- $componentEnabled := or (not (hasKey $values "enabled")) (get $values "enabled") -}}
{{- $global := mustMergeOverwrite (deepCopy ((get $values "global") | default dict)) $parentGlobal -}}
{{- $ctxValues := mustMergeOverwrite (deepCopy $values) (dict "global" $global) -}}
{{- $ctxChart := dict "Name" "prometheus-node-exporter" "Version" "4.47.0" "AppVersion" "1.9.1" -}}
{{- $ctx := dict "Values" $ctxValues "Release" .Release "Chart" $ctxChart "Capabilities" .Capabilities "Files" .Files "Template" .Template -}}
{{- if and (get $metricValues "enabled") $componentEnabled -}}
{{- with $ctx -}}
{{- $ctxRoot := . -}}
{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "childcharts.metric.prometheus-node-exporter.fullname" . }}
  namespace: {{ include "childcharts.metric.prometheus-node-exporter.namespace" . }}
  labels:
    {{- include "childcharts.metric.prometheus-node-exporter.labels" $ctxRoot | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.service.ipDualStack.enabled }}
  ipFamilies: {{ toYaml .Values.service.ipDualStack.ipFamilies | nindent 4 }}
  ipFamilyPolicy: {{ .Values.service.ipDualStack.ipFamilyPolicy }}
{{- end }}
{{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}
{{- if .Values.service.internalTrafficPolicy }}
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy }}
{{- end }}
  type: {{ .Values.service.type }}
{{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: "{{ .Values.service.clusterIP }}"
{{- end }}
  ports:
    - port: {{ .Values.service.servicePort | default .Values.service.port }}
      {{- if ( and (eq .Values.service.type "NodePort" ) (not (empty .Values.service.nodePort)) ) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "childcharts.metric.prometheus-node-exporter.selectorLabels" . | nindent 4 }}
{{- end }}

{{- end -}}
{{- end -}}
