{{- if and .Values.logging.enabled .Values.logging.elasticsearch.enabled .Values.logging.elasticsearch.secret.enabled -}}
{{- $passwordValue := (randAlphaNum 16) | b64enc | quote }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "elasticsearch.uname" . }}-credentials
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "elasticsearch.uname" . }}"
    {{- range $key, $value := .Values.logging.elasticsearch.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  username: {{ "elastic" | b64enc }}
  {{- if .Values.logging.elasticsearch.secret.password }}
  password: {{ .Values.logging.elasticsearch.secret.password | b64enc }}
  {{- else }}
  password: {{ $passwordValue }}
  {{- end }}
{{- end }}
