{{- if and .Values.logging.enabled .Values.logging.elasticsearch.enabled .Values.logging.elasticsearch.service.enabled -}}
---
kind: Service
apiVersion: v1
metadata:
{{- if eq .Values.logging.elasticsearch.nodeGroup "master" }}
  name: {{ template "elasticsearch.masterService" . }}
{{- else }}
  name: {{ template "elasticsearch.uname" . }}
{{- end }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "elasticsearch.uname" . }}"
{{- if .Values.logging.elasticsearch.service.labels }}
{{ toYaml .Values.logging.elasticsearch.service.labels | indent 4}}
{{- end }}
  annotations:
{{ toYaml .Values.logging.elasticsearch.service.annotations | indent 4 }}
spec:
  type: {{ .Values.logging.elasticsearch.service.type }}
  selector:
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "elasticsearch.uname" . }}"
  publishNotReadyAddresses: {{ .Values.logging.elasticsearch.service.publishNotReadyAddresses }}
  ports:
  - name: {{ .Values.logging.elasticsearch.service.httpPortName | default "http" }}
    protocol: TCP
    port: {{ .Values.logging.elasticsearch.httpPort }}
{{- if .Values.logging.elasticsearch.service.nodePort }}
    nodePort: {{ .Values.logging.elasticsearch.service.nodePort }}
{{- end }}
  - name: {{ .Values.logging.elasticsearch.service.transportPortName | default "transport" }}
    protocol: TCP
    port: {{ .Values.logging.elasticsearch.transportPort }}
{{- if .Values.logging.elasticsearch.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.logging.elasticsearch.service.loadBalancerIP }}
{{- end }}
{{- with .Values.logging.elasticsearch.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml . | indent 4 }}
{{- end }}
{{- if .Values.logging.elasticsearch.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.logging.elasticsearch.service.externalTrafficPolicy }}
{{- end }}
{{- end }}

{{- if and .Values.logging.enabled .Values.logging.elasticsearch.enabled -}}
---
kind: Service
apiVersion: v1
metadata:
{{- if eq .Values.logging.elasticsearch.nodeGroup "master" }}
  name: {{ template "elasticsearch.masterService" . }}-headless
{{- else }}
  name: {{ template "elasticsearch.uname" . }}-headless
{{- end }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "elasticsearch.uname" . }}"
{{- if .Values.logging.elasticsearch.service.labelsHeadless }}
{{ toYaml .Values.logging.elasticsearch.service.labelsHeadless | indent 4 }}
{{- end }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None # This is needed for statefulset hostnames like elasticsearch-0 to resolve
  # Create endpoints also if the related pod isn't ready
  publishNotReadyAddresses: true
  selector:
    app: "{{ template "elasticsearch.uname" . }}"
  ports:
  - name: {{ .Values.logging.elasticsearch.service.httpPortName | default "http" }}
    port: {{ .Values.logging.elasticsearch.httpPort }}
  - name: {{ .Values.logging.elasticsearch.service.transportPortName | default "transport" }}
    port: {{ .Values.logging.elasticsearch.transportPort }}
{{- end -}}
