{{- $values := include "childcharts.metric.kube-state-metrics.values" . | fromYaml -}}
{{- $metricValues := get .Values "metric" | default dict -}}
{{- $extraValues := get $metricValues "extra" | default dict -}}
{{- $parentGlobal := get $extraValues "global" | default dict -}}
{{- $componentEnabled := or (not (hasKey $values "enabled")) (get $values "enabled") -}}
{{- $global := mustMergeOverwrite (deepCopy ((get $values "global") | default dict)) $parentGlobal -}}
{{- $ctxValues := mustMergeOverwrite (deepCopy $values) (dict "global" $global) -}}
{{- $ctxChart := dict "Name" "kube-state-metrics" "Version" "5.37.0" "AppVersion" "2.15.0" -}}
{{- $ctx := dict "Values" $ctxValues "Release" .Release "Chart" $ctxChart "Capabilities" .Capabilities "Files" .Files "Template" .Template -}}
{{- if and (get $metricValues "enabled") $componentEnabled -}}
{{- with $ctx -}}
{{- $ctxRoot := . -}}
{{- if and (eq  .Values.rbac.create true) (eq .Values.rbac.useClusterRole false) -}}
{{- range (join "," $ctxRoot.Values.namespaces) | split "," }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "childcharts.metric.kube-state-metrics.labels" $ctxRoot | indent 4 }}
  name: {{ template "childcharts.metric.kube-state-metrics.fullname" $ctxRoot }}
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
{{- if (not $ctxRoot.Values.rbac.useExistingRole) }}
  name: {{ template "childcharts.metric.kube-state-metrics.fullname" $ctxRoot }}
{{- else }}
  name: {{ $ctxRoot.Values.rbac.useExistingRole }}
{{- end }}
subjects:
- kind: ServiceAccount
  name: {{ template "childcharts.metric.kube-state-metrics.serviceAccountName" $ctxRoot }}
  namespace: {{ template "childcharts.metric.kube-state-metrics.namespace" $ctxRoot }}
{{- end -}}
{{- end -}}

{{- end -}}
{{- end -}}
