{{- $values := include "childcharts.metric.kube-state-metrics.values" . | fromYaml -}}
{{- $metricValues := get .Values "metric" | default dict -}}
{{- $extraValues := get $metricValues "extra" | default dict -}}
{{- $parentGlobal := get $extraValues "global" | default dict -}}
{{- $componentEnabled := or (not (hasKey $values "enabled")) (get $values "enabled") -}}
{{- $global := mustMergeOverwrite (deepCopy ((get $values "global") | default dict)) $parentGlobal -}}
{{- $ctxValues := mustMergeOverwrite (deepCopy $values) (dict "global" $global) -}}
{{- $ctxChart := dict "Name" "kube-state-metrics" "Version" "5.37.0" "AppVersion" "2.15.0" -}}
{{- $ctx := dict "Values" $ctxValues "Release" .Release "Chart" $ctxChart "Capabilities" .Capabilities "Files" .Files "Template" .Template -}}
{{- if and (get $metricValues "enabled") $componentEnabled -}}
{{- with $ctx -}}
{{- $ctxRoot := . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "childcharts.metric.kube-state-metrics.fullname" . }}
  namespace: {{ template "childcharts.metric.kube-state-metrics.namespace" . }}
  labels:
    {{- include "childcharts.metric.kube-state-metrics.labels" . | indent 4 }}
  annotations:
    {{- if .Values.prometheusScrape }}
    prometheus.io/scrape: '{{ .Values.prometheusScrape }}'
    {{- end }}
    {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: "{{ .Values.service.type }}"
  {{- if .Values.service.ipDualStack.enabled }}
  ipFamilies: {{ toYaml .Values.service.ipDualStack.ipFamilies | nindent 4 }}
  ipFamilyPolicy: {{ .Values.service.ipDualStack.ipFamilyPolicy }}
  {{- end }}
  ports:
  - name: "http"
    protocol: TCP
    port: {{ .Values.service.port | default 8080}}
  {{- if ( and (eq .Values.service.type "NodePort" ) (not (empty .Values.service.nodePort)) ) }}
    nodePort: {{ .Values.service.nodePort }}
  {{- end }}
    targetPort: {{ .Values.service.port | default 8080}}
  {{ if .Values.selfMonitor.enabled }}
  - name: "metrics"
    protocol: TCP
    port: {{ .Values.selfMonitor.telemetryPort | default 8081 }}
    targetPort: {{ .Values.selfMonitor.telemetryPort | default 8081 }}
  {{- if ( and (eq .Values.service.type "NodePort" ) (not (empty .Values.service.nodePort)) ) }}
    nodePort: {{ .Values.selfMonitor.telemetryNodePort }}
  {{- end }}
  {{ end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
{{- if .Values.autosharding.enabled }}
  clusterIP: None
{{- else if .Values.service.clusterIP }}
  clusterIP: "{{ .Values.service.clusterIP }}"
{{- end }}
  selector:
    {{- include "childcharts.metric.kube-state-metrics.selectorLabels" . | indent 4 }}

{{- end -}}
{{- end -}}
